### ISSUE TITLE
Is getting kubectl actionable?

### ISSUE THREAD

**Issue by castrojo** [juju-solutions/bundle-kubernetes-core#10]
Right now we do: 

    juju scp kubernetes/<leader-unit-number>:kubectl_package.tar .
    tar zxf kubectl_package.tar

I wonder if an action could clean this up, something like 

   juju run-action get-tools kubernetes/0

**Comment by marcoceppi** [comment]
no, you can not transfer files over actions.

**Comment by chuckbutler** [comment]
I think we could add an action to regenerate the client package... but that doesn't solve the delivery commands.
