### ISSUE TITLE
Need a better kubectl experience

### ISSUE THREAD

**Issue by castrojo** [juju-solutions/bundle-kubernetes-core#12]
Right now we expect the user to scp down a kubeconfig file and then pass it along to the CLI tool for every command.

Marco's mentioned this aloud, I'll put this here as a starter for the conversation:

- If the user is new, aka, `~/.kube` doesn't exist, copy the config over.
- If `~/.kube` exists, then we know the user is already using k8s and knows how to manage their creds, so we should NOT clober their existing creds, instead document how to use our creds with their existing setups.

**Comment by mbruzek** [comment]
Yeah @chuckbutler and I talked about writing some kind of a program that would merge into an existing config. Now the question is: How would we install a program on the clients?

**Comment by chuckbutler** [comment]
@mbruzek - i wonder if our snap package that we've done for kubectl, if we don't put in some additional non-vanilla helpers in there that we can pipeline into the snap. 

This gives us an interesting possibility to augment kubectl. 

We can add something like juju-kube get-credentials.

It parses juju run --application kubernetes is-leader

Fetches the kubectl package, determines $SNAP_USER_DATA and merges / adds the configuration. This gives us a pipeline to ship the tooling that will work on the linux distros (good first target) and we can sort out how this would work for the OS X crowd. As our kubectl package is only shipping for ELF binary compliant systems right now anyway.

**Comment by chuckbutler** [comment]
I feel like this was covered in the README of CDK and our rewrite addressed this concern. Please re-open if this is not the case
