### ISSUE TITLE
TLS certificate issues (again)

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-kubernetes-core#16]
In the reverse proxy logs I am seeing:

```
time="2016-08-26T09:44:33Z" level=error msg="Error watching kubernetes events: failed to create watch: failed to do version request: GET \"https://10.1.0.1:443/apis/extensions/v1beta1/ingresses\" : failed to create request: GET \"https://10.1.0.1:443/apis/extensions/v1beta1/ingresses\" : [Get https://10.1.0.1:443/apis/extensions/v1beta1/ingresses: x509: certificate signed by unknown authority]"
time="2016-08-26T09:44:34Z" level=error msg="Kubernetes connection error failed to create watch: failed to do version request: GET \"https://10.1.0.1:443/apis/extensions/v1beta1/ingresses\" : failed to create request: GET \"https://10.1.0.1:443/apis/extensions/v1beta1/ingresses\" : [Get https://10.1.0.1:443/apis/extensions/v1beta1/ingresses: x509: certificate signed by unknown authority], retrying in 1m27.681275726s"
```

The x509 errors seem to be surfacing due to either the CA not being imported, or the server cert not being generated with the proper SANS. 

Upon inspecting the cert it appears it has all the required information:

```
  X509v3 Subject Alternative Name:
                IP Address:10.1.0.1, DNS:kubernetes, DNS:kubernetes.cluster.local, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:104.155.173.203, IP Address:10.128.0.6, DNS:juju-11383a-3
```

Upon inspecting the root cert being missing from the keychain, even after validating the cert placed in /usr/local/share/ca-certificates/kubernetes.crt, and re-running `sudo update-ca-certificates` the certificate response is still one of an x509 signing error.

**Comment by mbruzek** [comment]
@jamesbeedy notified me of a potential bug in the tls layer yesterday. These two do not seem related but we should take a look at rebuilding the kubernetes charm with the PR that I just merged. https://github.com/juju-solutions/layer-tls/pull/44

**Comment by jamesbeedy** [comment]
@mbruzek https://github.com/battlemidget/juju-layer-ruby/pull/6

The os.chdir was causing other code to execute in the chdir <- this is why tls-layer couldn't find the config or cert even though they were there.

**Comment by chuckbutler** [comment]
No longer using the same charm(s) this bundle was filed against. If this continues to be an issue please re-open and re-state the problem domain with requisit logs and status output.
