### ISSUE TITLE
persistent ESB volume for etcd

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-kubernetes-core#36]
etcd unit should have a persistent ESB volume, that should allow easier to recover etcd if VM reboots.

Core bundle is very handy for dev/test cluster, so persistent volume for etcd would be nice to have.

**Comment by ktamiola** [comment]
Very good point. VM shutdown messes up the whole setup!

**Comment by marcoceppi** [comment]
Closing as duplicate of https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/127 Once that's updated, since the etcd in both bundles is the same charm, it'll be reflected here.

**Comment by ktamiola** [comment]
@marcoceppi Thank you!
