### ISSUE TITLE
Feature request: graceful shutdown and/or etcd backup

### ISSUE THREAD

**Issue by ktamiola** [juju-solutions/bundle-kubernetes-core#37]
The rev. 10 `kubernetes core` deploys and runs like a true charm. 👍  for authors! However, it would be amazingly useful to have a **graceful shutdown _and/or_ backup routine** for single-node `etcd`. (I am a aware a backup of multi-unit `etcd` is complicated.

**Comment by marcoceppi** [comment]
@chuckbutler far off is this from the current backup/restore work?

**Comment by ktamiola** [comment]
@marcoceppi @chuckbutler is there a way we can get with testing? Adding restore / backup to this charm will be a major feature, as there are numbers of *sys admins* upset about the `etcd` recovery hurdle.

**Comment by chuckbutler** [comment]
@ktamiola - yep, etcd is in the edge channel with the snapshot/restore

https://jujucharms.com/etcd/16

There's a rundown of how to use the feature in the readme. I'm highly interested in hearing your feedback on how the migration went in your evaluation(s)

Thanks for giving it a look and filing the bug @ktamiola

**Comment by ktamiola** [comment]
Splendid! Thank you @chuckbutler ! We will give it a go ASAP. Thank you so much for taking time and answering so quickly. 

As a side note: we have experimented with multiple deployment options for `kubernetes` on our custom MAAS installation and Juju + your charms is a breeze compared to alternatives!

**Comment by chuckbutler** [comment]
Thats fantastic :) Thanks for the early feedback. Let us know if there's anything else we can do to make it even better.

**Comment by ktamiola** [comment]
My pleasure @chuckbutler ! We will be loud and verbal!

**Comment by chuckbutler** [comment]
This appears to be completed, and hasn't been active for 30 days. I'm going to close this bug, and if it's still troubling you feel free to re-open and we can circle back.
