### ISSUE TITLE
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

### ISSUE THREAD

**Issue by canonical-cgregan** [juju-solutions/bundle-kubernetes-core#43]
Xenial
juju 2
Maas 2

Kubernetes worker fails to install due to operand error. 
https://pastebin.canonical.com/173432/

Steps:
1) Bootstrap juju 2.0.2 controller for MAAS 2.1.2
2) Deploy Kubernetes-core

**Comment by marcoceppi** [comment]
Is this a limited egress environment? The error is bad, but it looks like a lot of connection failures

**Comment by chuckbutler** [comment]
I'm not 100% positive this is the root suspect but: 

```
2016-12-13 02:11:13 INFO install ERROR (2) running ['/var/lib/juju/agents/unit-kubernetes-worker-0/charm/exec.d/docker-compose/charm-pre-install']
2016-12-13 02:11:13 INFO install STDOUT<<EOM
2016-12-13 02:11:13 INFO install None
2016-12-13 02:11:13 INFO install EOM

```

This looks like pip install docker-compose and pip3 install docker-compose failed. This is a leftover from layer-docker that can be safely omitted in the kubernetes charms. I'll make sure we file an issue on k8s to get that excluded from the next published build.

However, if you're interested in the resolution i've filed: https://github.com/juju-solutions/layer-docker/issues/98

**Comment by marcoceppi** [comment]
Please re-open this against [juju-solutions/bundle-canonical-kubernetes](https://github.com/juju-solutions/bundle-canonical-kubernetes) if it still persists.
