### ISSUE TITLE
`juju add-unit kubernetes-worker --constraints` is giving errors

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-kubernetes-core#49]
`juju add-unit kubernetes-worker --constraints "cpu-cores=8 mem=32G"`
`error: flag provided but not defined: --constraints`

I'm using the latest Mac juju cli v2.0.2

**Comment by rimusz** [comment]
I can only get working with:
```
$ juju set-constraints kubernetes-worker instance-type=t2.medium root-disk=200G
$ juju add-unit kubernetes-worker -n 1
```

**Comment by marcoceppi** [comment]
Please re-open this against [juju-solutions/bundle-canonical-kubernetes](https://github.com/juju-solutions/bundle-canonical-kubernetes) if it still persists.
