### ISSUE TITLE
Readme deploy instructions could use conjure-up like the canonical-kubernetes Readme

### ISSUE THREAD

**Issue by mikemccracken** [juju-solutions/bundle-kubernetes-core#51]
If we're leading with conjure-up for deploy instructions in the canonical-kubernetes bundle, let's do it for this one too.

**Comment by marcoceppi** [comment]
This repo is being deprecated

**Comment by marcoceppi** [comment]
Please re-open this against [juju-solutions/bundle-canonical-kubernetes](https://github.com/juju-solutions/bundle-canonical-kubernetes) if it still persists.
