### ISSUE TITLE
Support basic auth

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/bundle-kubernetes-core#52]
Is it possible to support basic auth?

- `kubectl` doesn't seem to be available for Windows
- generating the client certificates and configuring the browser correctly is quite tedious for testing

This would mostly be to get the user testing out kubernetes as quickly as possible, so just one auto-generated username-password combination would be enough, I think.

**Comment by galgalesh** [comment]
@chuckbutler Is this the correct place for issues/feature requests for the kubernetes core bundle?

**Comment by marcoceppi** [comment]
The core bundle is in the cdk bundle. All feature requests should be made
there
