### ISSUE TITLE
This repo can be removed.

### ISSUE THREAD

**Issue by wwwtyro** [juju-solutions/bundle-kubernetes-core#54]
Everything now being maintained in bundle-canonical-kubernetes.

**Comment by galgalesh** [comment]
@marcoceppi @chuckbutler @mbruzek 

Does anyone have the correct permissions to remove this repo? This repo causes some confusion. PS: also update the bugs-url of the bundle in the store: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/217

**Comment by marcoceppi** [comment]
Removing and repointing
