### ISSUE TITLE
Recommending bigger root-disk for master

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-kubernetes-core#55]
When deploying this bundle, if kept up for more than a couple of weeks, the easy-rsa lxd container will grow to something like 5GB to 6GB (and probably keep growing thereafter). 

As a result, using a default 8GB root-disk results in problems of disk space pretty quickly. 

One solution is to use a larger disk, which, on most clouds, would work nicely using a constraint on the master. If you agree with this solution I'll do a PR. 

Additionally, if users encounter this issue, they require some knowledge of zfs and lxd to grow storage and make sure their solution keeps running. Therefore, I also propose to add a section in the docs about this situation
@castrojo do you think this would be worth putting in our operational constraints section?

**Comment by marcoceppi** [comment]
What is growing? Log data?

**Comment by SaMnCo** [comment]
I have a hard time identifying that actually. There aren't a lot of logs, it seems to be zfs asking for more space. Logs where in the MBs of data, not much, but 8GB as the default root disk is very very small so it triggered my monitoring alerts very quickly. 
The trigger is 20% disk space left, which is a default of my monitoring solution. I would expect others to bump into this as well. 

I'll dig into what's getting bigger.

**Comment by marcoceppi** [comment]
Please re-open this against [juju-solutions/bundle-canonical-kubernetes](https://github.com/juju-solutions/bundle-canonical-kubernetes) if it still persists.
